name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Atharv22-gt
          outputs: dist/snake.svg

      - name: Push snake.svg to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git switch --orphan output
          rm -rf ./*
          cp dist/snake.svg ./snake.svg
          git add snake.svg
          git commit -m "chore: update snake animation"
          git push -f origin output
